version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/domain.crt:/etc/ssl/certs/domain.crt
      - ./certs/private.key:/etc/ssl/private/private.key
      - ./certs/ca_bundle.crt:/etc/ssl/certs/ca_bundle.crt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public
    depends_on:
      - web

  web:
    env_file: "../nft_marketplace/.env"
    container_name: nft-web
    image: ton-nft-web:latest
    build:
      context: ../nft_marketplace
      dockerfile: ../nft_marketplace/Dockerfile
    ports:
      - "8080:8000"
    networks:
      - private
      - public

networks:
  public:
    driver: bridge
  private:
    driver: bridge